<?php

// client side action specific functionality
$this->headScript()->appendFile('/js/specialists.js');

// client side action specific functionality
$this->headScript()->appendFile('/js/user-profile.js');

$this->headLink()->appendStylesheet('/css/user-profile.css');

// load custom title
$this->headTitle($this->T('site-window-title'));

$this->headMeta()
	->setName('description', $this->T('meta-description'))
	->setName('keywords', $this->T('meta-keywords'));

// get locale to use for interface
$loc = $this->getLocale();

?>

<table width="100%" cellspacing="0" cellpadding="20px">
<?php foreach ($this->items as $item):?>
<tr>
	<td valign="top">
	<span class="editable name" id="name-<?php echo $item->id ?>"><?php echo $item->name ?></span>
	<span class="editable phone" id="phone-<?php echo $item->id ?>"><?php echo $item->phone ?></span>
	</td>
	<td valign="top"><span class="editable-area description" id="description-<?php echo $item->id ?>"><?php echo $item->description ?></span></td>
	<td><a href="<?php echo $this->url(	array(
		'lang' => $this->getLocale(),
		'controller' => 'new',
		'action' => 'delete',
		'module' => 'clads',
		'id' => $item->id,
	)
	,'default'); ?>" onclick="return confirm('<?php echo $this->_('are-you-sure') ?>')"><img src="/images/feedback-form/no.png" alt="<?php echo $this->_('remove-action') ?>" border="" /></a></td>
</tr>
<?php endforeach; ?>
<tr>
	<td colspan="3"><a id="add-button" href="<?php echo $this->url(	array(
		'lang' => $this->getLocale(),
		'controller' => 'new',
		'action' => 'index',
		'module' => 'clads',
	)
	,'default'); ?>">додати ще одне оголошення</a></td>
</tr>
</table>

<?php /* ?>

<h1>Аналітика</h1>

<h2>Покази в результатах пошуку</h2>

<h2>Перегляди за містами</h2>



<h2><?php echo $this->T('country-administrative-districts') ?></h2>

<div class="tag-cloud">
<?php foreach ($this->regions as $region): ?>
<a href="<?php echo $this->url(array('id' => $region->region_id, 'action' => 'region'), 'default') ?>"><?php echo ($loc == 'uk') ? $region->name_uk : $region->name ?></a>
<?php endforeach; ?>
</div>

<?php */ ?>