<?php
// client side action specific functionality
$this->headScript()->appendFile('/js/specialists.js');

// load custom title
$this->headTitle($this->T('site-window-title'));

$this->headMeta()
	->setName('description', $this->T('meta-description'))
	->setName('keywords', $this->T('meta-keywords'));

// get locale to use for interface
$loc = $this->getLocale();
?>
<div class="city-finder">
<h1><?php echo $this->T('in-what-city-you-are-right-now'); ?></h1>

<div><?php echo $this->T('in-what-city-you-are-right-now-description'); ?></div>

<select id="city-finder-regions" class="finder-selectbox-control">
<option value="0">[ <?php echo $this->T('select-country-region'); ?> ]</option>
<?php foreach ($this->regions as $region): ?>
<option value="<?php echo $region->region_id ?>"><?php echo ($loc == 'uk') ? $region->name_uk : $region->name ?></option>
<?php endforeach; ?>
</select>
<select id="city-finder-city" class="finder-selectbox-control hidden-element"></select>
</div>

<p><?php echo $this->T('beta-welcome-text') ?></p>

<h2><?php echo $this->T('country-administrative-districts') ?></h2>

<div class="tag-cloud">
<?php foreach ($this->regions as $region): ?>
<a href="<?php echo $this->url(array('id' => $region->region_id, 'action' => 'region'), 'default') ?>"><?php echo ($loc == 'uk') ? $region->name_uk : $region->name ?></a>
<?php endforeach; ?>
</div>