<?php
// client side action specific functionality
$this->headScript()->appendFile('/js/specialists.js');

// load custom title
$this->headTitle($this->T('site-window-title'));

// get locale to use for interface
$loc = $this->getLocale();
?>
<div class="city-finder">
<h1><?php echo $this->T('in-what-city-you-are-right-now'); ?></h1>

<div><?php echo $this->T('in-what-city-you-are-right-now-description'); ?></div>

<select id="city-finder-regions" class="finder-selectbox-control">
<option value="0">[ <?php echo $this->T('select-country-region'); ?> ]</option>
<?php foreach ($this->regions as $region): ?>
<option value="<?php echo $region->region_id ?>"><?php echo ($loc == 'uk') ? $region->name_uk : $region->name ?></option>
<?php endforeach; ?>
</select>

<select id="city-finder-city" class="finder-selectbox-control hidden-element"></select>

</div>

<div class="services-finder">
<h1><?php echo $this->T('what-type-of-service'); ?></h1>
<div><?php echo $this->T('what-type-of-service-description'); ?></div>

<input type="text" id="services-finder-select-control" class="finder-select-control" />

<div id="services-list">
<?php foreach ($this->services as $service): ?>
<div class="service"><a href="<?php echo $this->url(array('lang' => $this->getLocale(), 'service' => ($loc == 'uk') ? $service->seo_name_uk : $service->seo_name) ,'services_lang'); ?>"><?php echo ($loc == 'uk') ? $service->name_uk : $service->name ?></a></div>
<?php endforeach; ?>
</div>

</div>