<?php

if( !function_exists('ceiling') )
{
    function ceiling($number, $significance = 1)
    {
        return ( is_numeric($number) && is_numeric($significance) ) ? (ceil($number/$significance)*$significance) : false;
    }
}

?>
<div id="search-panel-main" class="search-panel">
	<div class="search-form-column-city">
		<div class="item-title-main-block">
		<span class="item-title-main"><?php echo ($this->getLocale() == 'uk') ? $this->city->name_uk : $this->city->name ?></span>
		</div>

		<?php if ($this->city_near): ?>
		<div class="label"><?php echo $this->T('closest-towns');?></div>
		<?php foreach ($this->city_near as $city):
		
		if (empty($this->extraCities)) {
			
			$url = $this->url(array('also_search' =>  $city->city_id, 'page' => 1));
			$checked = false;
			
		} else {
		
			if (in_array($city->city_id, $this->extraCities)) {
				$newCities = array_diff($this->extraCities, array($city->city_id));
				if (!empty($newCities)) {
					$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
				} else {
					$url = $this->url(array('page' => 1, 'also_search' => null));
				}
				$checked = true;
			} else {
				$newCities = array_merge($this->extraCities, array($city->city_id));
				$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
				$checked = false;
			}
		}
		?>
		<div class="item-element">
			<input <?php if ($checked === true) :?> checked="checked" <?php endif;?> value="<?php echo $url ?>" type="checkbox" id="including-close-cities-<?php echo $city->city_id ?>" /><label for="including-close-cities-<?php echo $city->city_id ?>" class="item-title"><?php echo ($this->getLocale() == 'uk') ? $city->name_uk : $city->name ?></label>
			<span class="label">~<?php echo ceiling($city->distance, 10) ?> км</span>
		</div>
		<?php endforeach; ?>
		<?php endif; ?>

		<?php if ($this->city_large): ?>
		<div class="label"><?php echo $this->T('closest-large-cities');?></div>
		<?php foreach ($this->city_large as $city):
		
		if (empty($this->extraCities)) {
			
			$url = $this->url(array('also_search' =>  $city->city_id, 'page' => 1));
			$checked = false;
			
		} else {
		
			if (in_array($city->city_id, $this->extraCities)) {
				$newCities = array_diff($this->extraCities, array($city->city_id));
				if (!empty($newCities)) {
					$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
				} else {
					$url = $this->url(array('page' => 1, 'also_search' => null));
				}
				$checked = true;
			} else {
				$newCities = array_merge($this->extraCities, array($city->city_id));
				$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
				$checked = false;
			}
		}
		?>
		<div class="item-element">
			<input <?php if ($checked === true) :?> checked="checked" <?php endif;?> value="<?php echo $url ?>"  type="checkbox" id="including-close-cities-<?php echo $city->city_id ?>" /><label for="including-close-cities-<?php echo $city->city_id ?>" class="item-title"><?php echo ($this->getLocale() == 'uk') ? $city->name_uk : $city->name ?></label>
			<span class="label">~<?php echo ceiling($city->distance, 10) ?> км</span>
		</div>
		<?php endforeach; ?>
		<?php endif; ?>
	</div>
</div>