<?php
// get locale to use for interface
$loc = $this->getLocale();
?>
<div id="search-panel-main" class="search-panel">
	<h2><?php echo $this->T('specialists-search'); ?></h2>
</div>
<div id="search-panel-regions" class="search-panel">
<div><?php echo $this->T('specify-the-region'); ?></div>
<div class="city-finder">
<?php foreach ($this->regions as $region): ?>
<a class="region-link <?php if ($this->currentRegion == $region->region_id): echo 'region-link-active'; endif; ?>" href="<?php echo $this->url(array('id' => $region->region_id, 'action' => 'region'), 'default') ?>"><?php echo ($loc == 'uk') ? $region->name_uk : $region->name ?></a>
<?php endforeach; ?>
</div>
</div>