<?php $this->headTitle($this->T('help')); ?>
<h1><?php echo $this->T('search-form-usage'); ?></h1>
<p>article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage </p>

<p>article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage </p>

<p>article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage </p>

<p>article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage
article search-form-usage article search-form-usage article search-form-usage article search-form-usage </p>