<?php

// client side action specific functionality
$this->headScript()->appendFile('/js/login.js');

// load custom title
$this->headTitle($this->T('signin'));

?>

<h1><?php echo $this->T('signin'); ?></h1>

<p><?php echo $this->T('login-description'); ?></p>

<div id="vk_auth"></div>
<script type="text/javascript">
VK.Widgets.Auth("vk_auth", {width: "300px", onAuth: function(data) {
  location.href = '<?php echo '/' . $this->getLocale() . $this->getVk('auth_url') ?>'
				  + '?uid=' + data['uid']
				  + '&first_name=' + data['first_name']
				  + '&last_name=' + data['last_name']
				  + '&hash=' + data['hash'];
}});
</script>

<p><?php echo $this->T('login-post-description'); ?></p>

<?php /* echo $this->form */ ?>