<!DOCTYPE html>
<html dir="ltr" lang="<?php echo $this->getLocale() ?>">
<head>
  <meta charset="utf-8"/>
  <meta name="description" content="<?php echo $this->T('meta-description') ?>" />
  <meta name="keywords" content="<?php echo $this->T('meta-keywords') ?>" />
  <?php echo $this->headTitle($this->T('site-name'))->setSeparator(' :: ') ?>
  <?php echo $this->headLink()->appendStylesheet('/css/layout.css')
                              ->appendStylesheet('/css/search-form.css') ?>
  <?php echo $this->headScript()
  	->prependFile('/js/jquery-1.4.2.min.js') //TODO: move to CDN for 'production'
  	->appendFile('/js/search-form-actions.js'); ?>
  <?php if (APPLICATION_ENV == 'production' && !$this->isAdmin()): ?>
  <script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15610072-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
  <?php endif; ?>
</head>
<body>

<div id="page"><div id="page-inner">

<?php if ($this->isAdmin()):?>
<div style="width:99%;float:left;padding-bottom:30px;">
	<div style="float:left;">
		<a href="/">Search</a>
		<a href="/crawler/editor">Knowlage Base Editor</a>
		<a href="/users/feedback/list/">Feedbacks</a>
	</div>
	<div style="float: right;">
	<?php echo $this->profileLink(); ?>
	</div>
</div>
<?php else: ?>
<div id="header">
<div id="logo">
<a href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'index',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>" title="<?php echo $this->T('site-name') . ' - ' . $this->T('slogan') ?>">
<img alt="<?php echo $this->T('logo') . ' ' . $this->T('site-name') ?>" src="<?php echo $this->getImagesUrl() . 'nash-master-logo-' . $this->getLocale() . '.png' ?>" /></a>
<div id="beta-mark"><img alt="<?php echo $this->T('beta-version'); ?>" src="<?php echo $this->getImagesUrl() . 'beta.png'; ?>" /></div>
</div>
<div id="header-search-form">
	<div id="header-search-form-block">
		<span><?php echo $this->T('what-type-of-service-question') ?></span><br />
		<input tabindex="0" id="header-search-form-element" type="text" />
		<div id="header-selector">
			вид робіт: <a id="header-selector-services" href="#">Укладка кафельної плитки</a> регіон: <a href="#">Тернопіль</a>
		</div>
	</div>
</div>
</div>
<?php endif; ?>

<div id="main"><div id="page-content">
<?php echo $this->layout()->content ?>
</div></div>

<div id="footer">
	<div id="footer-feedback"><a id="feedbackLink" href="#"><?php echo $this->T('send-us-your-feedback') ?></a></div>
	<?php echo $this->feedbackForm(); ?>
	<div id="footer-language-selector"><?php echo $this->languageSelector() ?></div>
	<div id="copyright">&copy; 2011 nash-master.com</div>
</div>

</div></div>

</body>
</html>