<!DOCTYPE html>
<html dir="ltr" lang="<?php echo $this->getLocale() ?>">
<head>
  <meta charset="utf-8"/>
  <meta name="description" content="<?php echo $this->T('meta-description') ?>" />
  <meta name="keywords" content="<?php echo $this->T('meta-keywords') ?>" />
  <link rel="icon" href="/favicon.ico" type="image/x-icon" />
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <?php echo $this->headTitle($this->T('site-name'))->setSeparator(' ') ?>
  <?php echo $this->headLink()->prependStylesheet('/css/layout.css')
                              ->prependStylesheet('/css/search-form.css') ?>
  <?php if (APPLICATION_ENV == 'production'): ?>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
  <script src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
  <?php if (!$this->isAdmin()):?>
  <script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15610072-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
  <?php endif; ?>
  
  <?php else:
  	$this->headScript()
  	->prependFile('/js/jquery.tmpl.min.js')
	->prependFile('/js/jquery-1.4.2.min.js')
  	;
  endif; ?>

  <?php echo $this->headScript()
  	->appendFile('/js/search-form-actions.js')
  	->appendFile('/js/jquery.typing-0.2.0.min.js')
  	->appendFile('/js/jquery.form.js')
  	->appendFile('/js/autoresize.jquery.min.js')
  	;
  	?>
  <script>
  var locale = "<?php echo $this->getLocale() ?>";
  </script>
</head>
<body>
<div id="page"><div id="page-inner">
<div id="top-menu">
	<div id="top-menu-right">
		<a id="feedbackLink" title="<?php echo $this->T('send-us-your-feedback') ?>" href="#"><?php echo $this->T('feedback') ?></a>
		<?php /* ?>
		<a href="/login"><?php echo $this->T('login'); ?></a>
		<?php */ ?>
	</div>
	<div id="top-menu-left">
	<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'index'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'index',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('search'); ?></a>
	<?php /* ?>
	<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'catalog'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'catalog',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('catalog'); ?></a>
	<?php */ ?>
	<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'articles'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'articles',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('articles'); ?></a>
	<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'links'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'links',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('links'); ?></a>
	</div>
</div>


<?php if ($this->isAdmin()):?>
<div style="width:99%;float:left;padding-bottom:30px;">
	<div style="float:left;">
	<a href="/crawler/editor">Knowlage Base Editor</a>
	<a href="/crawler/relations">Synonyms Relations Management</a>
	</div>
	<div style="float: right;">
	<?php echo $this->profileLink(); ?>
	</div>
</div>
<?php else: ?>

<div id="header">
<div id="logo">
<?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'index'): ?>
<img alt="<?php echo $this->T('logo') . ' ' . $this->T('site-name') ?>" src="<?php echo $this->getImagesUrl() . 'nash-master-logo-' . $this->getLocale() . '.png' ?>" />
<?php else: ?>
<a href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'index',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>" title="<?php echo $this->T('site-name') . ' - ' . $this->T('slogan') ?>">
<img alt="<?php echo $this->T('logo') . ' ' . $this->T('site-name') ?>" src="<?php echo $this->getImagesUrl() . 'nash-master-logo-' . $this->getLocale() . '.png' ?>" /></a>
<?php endif; ?>
<div id="beta-mark"><img alt="<?php echo $this->T('beta-version'); ?>" src="<?php echo $this->getImagesUrl() . 'beta.png'; ?>" /></div>
</div>

<?php if (!empty($this->searchForm)): ?>
<div id="header-search-form" class="header-search-form-wide">
<div id="header-search-form-block">
<?php /* ?><!--  <span><?php echo $this->T('what-type-of-service-question') ?></span><br />  --><?php */ ?>
<input tabindex="1" maxlength="200" id="header-search-form-element" type="text" />
<div id="header-selector">
<a tabindex="3" id="header-selector-regions" href="#"><?php echo $this->renderRegions(); ?>&nbsp;</a>
<a tabindex="2" id="header-selector-services" href="#">&nbsp;</a>
</div>
</div>
</div>
<?php endif;?>
</div>
<?php endif; ?>

<div id="main"><div id="page-content">
<?php echo $this->layout()->content ?>
</div></div>

<div id="footer">
	<div id="footer-menu">
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'about-us'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'about-us',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('about-us'); ?></a>
	<?php /* ?>
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'news'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'news',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('news'); ?></a>
	<?php */ ?>
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'terms-and-conditions'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'terms-and-conditions',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('terms-and-conditions'); ?></a>
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'for-developers'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'for-developers',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('for-developers'); ?></a>
	<?php /* ?>
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'contacts'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'contacts',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('contacts'); ?></a>
	<?php */ ?>
		<a <?php if ($this->getModuleName() == 'default' && $this->getControllerName() == 'help'): ?>class="active"<?php endif; ?> href="<?php echo $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'help',
		'action' => 'index',
		'module' => 'default',
	)
	,'default'); ?>"><?php echo $this->T('help'); ?></a>
	</div>
	<div id="copyright">&copy; 2011 nash-master.com, <?php echo $this->languageSelector() ?></div>
</div>

<?php echo $this->feedbackForm(); ?>

</div></div>
</body>
</html>
