<?php

// client side action specific functionality
$this->headScript()->appendFile('/js/search-stat.js');

// get locale to use for interface
$loc = $this->getLocale();
$cityTitle = ($loc == 'uk') ? $this->city->name_uk : $this->city->name;
$citySeoTitle = ($loc == 'uk') ? $this->city->seo_name_uk : $this->city->seo_name;

$serviceTitle = ($loc == 'uk') ? $this->service->name_uk : $this->service->name;

// load custom title
$this->headTitle($this->T('services-in-city', $serviceTitle, $cityTitle));

$this->headMeta()->setName('description', $this->T('what-type-of-service-in-city', $cityTitle))
		->setName('keywords', $serviceTitle . ', ' . $cityTitle . ', ' . $this->T('meta-keywords'));


$this->addSubNavication($this->url(array('city' => $citySeoTitle), 'city_lang'), $this->T('return-to-city-page', $cityTitle) , 'back-button');

?>
<div class="services-finder">
<h1><?php echo $this->T('services-in-city', $serviceTitle, $cityTitle); ?></h1>
</div>

<?php if (count($this->data) < 1): ?>
<p><?php echo $this->t('no-search-results') ?></p>

<p>
<?php if (empty($this->extraCities)): ?>
	<?php echo $this->T('no-searrch-results-description', $cityTitle, mb_strtolower($serviceTitle));?>
<?php else:?>
	<?php echo $this->T('no-search-results-with-extras-description', mb_strtolower($serviceTitle));?>
<?php endif; ?>

<?php if ($this->city_large): ?>

<?php foreach ($this->city_large as $city):
if (empty($this->extraCities)) {
	$url = $this->url(array('also_search' =>  $city->city_id, 'page' => 1));
	$checked = false;
} else {
	if (in_array($city->city_id, $this->extraCities)) {
		$newCities = array_diff($this->extraCities, array($city->city_id));
		if (!empty($newCities)) {
			$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
		} else {
			$url = $this->url(array('page' => 1, 'also_search' => null));
		}
		$checked = true;
	} else {
		$newCities = array_merge($this->extraCities, array($city->city_id));
		$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
		$checked = false;
	}
}

if ($checked === false):
?>
<a href="<?php echo $url ?>"><?php echo ($this->getLocale() == 'uk') ? $city->name_uk : $city->name ?></a>,
<?php
endif;
endforeach; ?>
<?php endif; ?>

</p>

<h1><?php echo $this->T('is-that-your-specialization', $serviceTitle); ?></h1>
<p><?php echo $this->T('is-that-your-specialization-description', $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'login',
		'module' => 'default',
	)
	,'default'), mb_strtolower($serviceTitle)) ?></p>

<?php else: ?>

<div class="search-results">
<?php foreach ($this->data as $res): ?>
	<div class="search-results-item">
		<div class="title"><a target="_blank" href="<?php echo $res['url'] ?>"><?php echo $this->cuttext($res['title'], 70) ?></a></div>
		<div class="description"><?php echo $this->cuttext($res['description'], 100) ?></div>
		<a target="_blank" href="<?php echo $res['url'] ?>" class="url"><?php echo $res['url'] ?></a>
	</div>
<?php endforeach; ?>
<?php echo $this->paginationControl($this->data, 'Sliding', 'search_pagination_control.phtml'); ?>
</div>
<?php endif; ?>