<?php

// client side action specific functionality
$this->headScript()->appendFile('/js/search-stat.js');

// get locale to use for interface
$loc = $this->getLocale();
$cityTitle = ($loc == 'uk') ? $this->city->name_uk : $this->city->name;
$citySeoTitle = ($loc == 'uk') ? $this->city->seo_name_uk : $this->city->seo_name;

$serviceTitle = ($loc == 'uk') ? $this->service->name_uk : $this->service->name;

// load custom title
$this->headTitle($this->T('services-in-city', $serviceTitle, $cityTitle));

$this->headMeta()->setName('description', $this->T('what-type-of-service-in-city', $cityTitle))
		->setName('keywords', $serviceTitle . ', ' . $cityTitle . ', ' . $this->T('meta-keywords'));


// add breadcrump
$this->setBreadcrumbs(array(
	$this->_('site-name') => $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'index',
		'action' => 'index',
		'module' => 'default',
	)
	,'lang'),
	$cityTitle => $this->url(array('city' => $citySeoTitle), 'city_lang'),
	$serviceTitle => ''
));

?>
<div class="services-finder">
<h1><?php echo $this->T('services-in-city', $serviceTitle, $cityTitle); ?></h1>
</div>

<?php if (count($this->data) < 1): ?>
<p><?php echo $this->t('no-search-results') ?></p>

<p>
<?php

if (empty($this->extraCities)): ?>
	<?php echo $this->T('no-searrch-results-description', $cityTitle, mb_strtolower($serviceTitle));?>
<?php else:?>
	<?php echo $this->T('no-search-results-with-extras-description', mb_strtolower($serviceTitle));?>
<?php endif; ?>


<?php if ($this->city_large): ?>

<?php foreach ($this->city_large as $city):
if (empty($this->extraCities)) {
	$url = $this->url(array('also_search' =>  $city->city_id, 'page' => 1));
} else {
	if (in_array($city->city_id, $this->extraCities)) {
		$newCities = array_diff($this->extraCities, array($city->city_id));
		if (!empty($newCities)) {
			$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
		} else {
			$url = $this->url(array('page' => 1, 'also_search' => null));
		}
	} else {
		$newCities = array_merge($this->extraCities, array($city->city_id));
		$url = $this->url(array('also_search' =>  implode(',', $newCities), 'page' => 1));
	}
}

endforeach; ?>
<?php endif; ?>

</p>

<?php else: ?>

<div class="search-results">
<?php foreach ($this->data as $res): ?>
	<div class="search-results-item">
		<div class="title"><?php echo $this->cuttext($res['name'], 70) ?> <span class="phone"><?php echo $this->cuttext($res['phone'], 15) ?></span></div>
		<div class="description"><?php echo $this->cuttext($res['description'], 300) ?></div>
	</div>
<?php endforeach; ?>
<?php echo $this->paginationControl($this->data, 'Sliding', 'search_pagination_control.phtml'); ?>
</div>
<?php endif; ?>

<h1><?php echo $this->T('is-that-your-specialization', $serviceTitle); ?></h1>
<p><?php echo $this->T('is-that-your-specialization-description', $this->url(
	array(
		'lang' => $this->getLocale(),
		'controller' => 'login',
		'module' => 'default',
	)
	,'default'), mb_strtolower($serviceTitle)) ?></p>